# Generated by Django 4.0.3 on 2023-10-22 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xfactor_common',
            name='logged_name',
        ),
        migrations.RemoveField(
            model_name='xfactor_common_cache',
            name='logged_name',
        ),
        migrations.RemoveField(
            model_name='xfactor_daily',
            name='logged_name',
        ),
        migrations.AddField(
            model_name='xfactor_common',
            name='logged_name_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.xfactor_ncdb'),
        ),
        migrations.AddField(
            model_name='xfactor_common_cache',
            name='logged_name_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.xfactor_ncdb'),
        ),
        migrations.AddField(
            model_name='xfactor_daily',
            name='logged_name_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.xfactor_ncdb'),
        ),
    ]
