# Generated by Django 4.0.3 on 2023-10-27 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_xfactor_common_logged_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xfactor_common',
            name='logged_name_id',
            field=models.ForeignKey(db_column='logged_name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.xfactor_ncdb'),
        ),
        migrations.AlterField(
            model_name='xfactor_common_cache',
            name='logged_name_id',
            field=models.ForeignKey(db_column='logged_name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.xfactor_ncdb'),
        ),
        migrations.AlterField(
            model_name='xfactor_daily',
            name='logged_name_id',
            field=models.ForeignKey(db_column='logged_name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.xfactor_ncdb'),
        ),
    ]
