# Generated by Django 4.0.3 on 2023-10-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_xfactor_common_logged_name_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xfactor_common',
            name='ext_chr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='xfactor_common',
            name='ext_chr_ver',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='xfactor_common',
            name='ext_edg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='xfactor_common',
            name='ext_edg_ver',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='xfactor_common',
            name='ext_fir',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='xfactor_common',
            name='ext_fir_ver',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='xfactor_common',
            name='multi_boot',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xfactor_common',
            name='security1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xfactor_common',
            name='security1_ver',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xfactor_common',
            name='security2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xfactor_common',
            name='security2_ver',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xfactor_common',
            name='security3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xfactor_common',
            name='security3_ver',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xfactor_common',
            name='security4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xfactor_common',
            name='security4_ver',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xfactor_common',
            name='security5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xfactor_common',
            name='security5_ver',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xfactor_common',
            name='uuid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xfactor_common_cache',
            name='ext_chr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='xfactor_common_cache',
            name='ext_chr_ver',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='xfactor_common_cache',
            name='ext_edg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='xfactor_common_cache',
            name='ext_edg_ver',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='xfactor_common_cache',
            name='ext_fir',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='xfactor_common_cache',
            name='ext_fir_ver',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='xfactor_common_cache',
            name='multi_boot',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xfactor_common_cache',
            name='security1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xfactor_common_cache',
            name='security1_ver',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xfactor_common_cache',
            name='security2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xfactor_common_cache',
            name='security2_ver',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xfactor_common_cache',
            name='security3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xfactor_common_cache',
            name='security3_ver',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xfactor_common_cache',
            name='security4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xfactor_common_cache',
            name='security4_ver',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xfactor_common_cache',
            name='security5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xfactor_common_cache',
            name='security5_ver',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xfactor_common_cache',
            name='uuid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
